let text = "Hello World, Good Morning";
console.log(text.length);
console.log(text.charAt(2));
let part = text.slice(2, 8);
console.log(part);
part = text.slice(-2, -8);
console.log(part);
part = text.slice(-8, -2);
console.log(part);
part = text.slice(-8, 2);
console.log(part);
part = text.slice(2, -8);
console.log(part);
part = text.slice(-8);
console.log(part);
part = text.slice(2);
console.log(part);
part = text.substring(2, 8);
console.log(part);
part = text.substring(-2, -8);
console.log(part);
part = text.substring(-8, -2);
console.log(part);
part = text.substring(-8, 2);
console.log(part);
part = text.substring(2, -8);
console.log(part);
part = text.substring(-8);
console.log(part);
part = text.substring(2);
console.log(part);
console.log("Substr");
part = text.substr(2, 8);
console.log(part);
part = text.substr(-2, -8);
console.log(part);
part = text.substr(-8, -2);
console.log(part);
part = text.substr(-8, 2);
console.log(part);
part = text.substr(2, -8);
console.log(part);
part = text.substr(-8);
console.log(part);
part = text.substr(2);
console.log(part);